/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l073xx.h"
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// Initialization of peripherals

	GPIO_clock_INIT();
	UART2_INIT();

	// DEFINE THE PIN MODE

	GPIOA->MODER &= ~(3U << (2 * 5));  // Clear the mode bits for PA5   //10TH AND 11TH BITS ARE SET TO 0
	GPIOA->MODER |= (1U << (2 * 5));   // Set the mode bits to 01 (Output)// 10TH BIT IS SET TO 1


while(1){

for(uint32_t i = 0 ; i<10000 ; i++ );
	GPIOA->ODR ^= GPIO_ODR_OD5;
}


}

void GPIO_clock_INIT(void ){

	//ENABLE GPIO A CLOCK
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
	//ENABLE GPIO B CLOCK
	RCC->IOPENR |= RCC_IOPENR_GPIOBEN;
	//ENABLE GPIO C CLOCK
	RCC->IOPENR |= RCC_IOPENR_GPIOCEN;
	//ENABLE GPIO D CLOCK
	RCC->IOPENR |= RCC_IOPENR_GPIODEN;
	//ENABLE GPIO E CLOCK
	RCC->IOPENR |= RCC_IOPENR_GPIOEEN;
}
void UART2_INIT(void){
      //ENABLE THE UART2 CLOCK
	 RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
	 // CONFIGURE THE UART2
	 USART2->BRR = 16000000 / 9600;   // Baudrate = 9600 (16 MHz clock)

	 USART2->CR1 = USART_CR1_TE |     // Enable transmitter
	               USART_CR1_RE |     // Enable receiver
	               USART_CR1_UE;      // Enable USART2
	 //configure the PINS PA2 AND PA3 AS ALTERNATE FUNCTION
	 GPIOA->MODER &= ~((3U << (2 * 2)) | (3U << (2 * 3)));// Clear bits
	 GPIOA->MODER |= (2U << (2 * 2)) | (2U << (2 * 3));    // Set alternate function mode


	 GPIOA->AFR[0] &= ~((0xF << (4 * 2)) | (0xF << (4 * 3))); // Clear AF bits
	 GPIOA->AFR[0] |= (4U << (4 * 2)) | (4U << (4 * 3));      // Set AF4 for USART2
}
